title: Mohammed Alnemari — Edge AI Researcher
name: Mohammed Alnemari
position: Assistant Professor & Department Chair
affiliation: Department of Computer Engineering, University of Tabuk
affiliation2: AIST Research Center, University of Tabuk
email: mnemari@ut.edu.sa
orcid: 0000-0002-5971-6703
twitter_username: alnemari-m
github_username: alnemari-m
google_scholar: ukW6rG0AAAAJ

baseurl: ""
url: "https://alnemari-m.github.io/"

theme: minima
plugins:
  - jekyll-feed

sass:
  style: compress
